### ISSUE TITLE
demo UI

### ISSUE THREAD

**Issue by simevo** [bluesky-social/adx#113]
Having some sort of UI for seeing in real time what happens in the demo would help people understand what's going on.

On top of #110 we could add the `ui1` and `ui2` services, each running a tiny vuejs app that show a reactive, live view of the feed/timeline.

As a plus, one could have a `/data` route that shows the Merkle DAG in a user-friendly way.

**Comment by dholms** [comment]
We discussed a demo UI, but decided not to go that route because we wanted the focus to be on the technical underpinnings & not the presentation.

As we push this along & things start to cohere, we'll revisit a UI 👌 

There is a great PL utility for exploring CAR files here: https://explore.ipld.io/
You can export a repo use `yarn cli export` and upload it to traverse the Merkle DAG. It's pretty neat :)
