### ISSUE TITLE
error /home/raphy/adx/node_modules/@vscode/sqlite3: Command failed.

### ISSUE THREAD

**Issue by raphael10-collab** [bluesky-social/adx#127]
(base) raphy@pc:~$ git clone https://github.com/bluesky-social/adx.git
    Cloning into 'adx'...
    remote: Enumerating objects: 2865, done.
    remote: Counting objects: 100% (286/286), done.
    remote: Compressing objects: 100% (86/86), done.
    remote: Total 2865 (delta 215), reused 201 (delta 200), pack-reused 2579
    Receiving objects: 100% (2865/2865), 14.78 MiB | 18.15 MiB/s, done.
    Resolving deltas: 100% (1779/1779), done.
    (base) raphy@pc:~$ cd adx/
    (base) raphy@pc:~/adx$ yarn
    yarn install v1.22.18
    [1/5] Validating package.json...
    [2/5] Resolving packages...
    [3/5] Fetching packages...
    [4/5] Linking dependencies...
    warning "workspace-aggregator-c0efa86d-08e7-43e5-8716-5f449fa1807f > @adx/common > ts-node@10.7.0" has unmet peer dependency "@types/node@*".
    [5/5] Building fresh packages...
    [1/3] ⠂ leveldown
    [2/3] ⠂ @vscode/sqlite3
    error /home/raphy/adx/node_modules/@vscode/sqlite3: Command failed.
    Exit code: 127
    Command: node-gyp rebuild
    Arguments: 
    Directory: /home/raphy/adx/node_modules/@vscode/sqlite3
    Output:
    /home/raphy/.nvm/versions/node/v16.15.0/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: 5: /home/raphy/.nvm/versions/node/v14.17.0/lib/node_modules/node-gyp/bin/node-gyp.js: not found

**Comment by dholms** [comment]
hard to know without seeing your system

maybe try wiping the `node-gyp` cache & trying again?
https://github.com/nodejs/node-gyp/issues/809#issuecomment-155019383

Otherwise, node-gyp has some system dependencies that may be required: 
https://github.com/nodejs/node-gyp

---
_copy/pasted from above_

### On Unix
Python v3.7, v3.8, v3.9, or v3.10
make
A proper C/C++ compiler toolchain, like [GCC](https://gcc.gnu.org/)

### On macOS
ATTENTION: If your Mac has been upgraded to macOS Catalina (10.15), please read [macOS_Catalina.md](https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md).

Python v3.7, v3.8, v3.9, or v3.10
XCode Command Line Tools which will install clang, clang++, and make.
Install the XCode Command Line Tools standalone by running xcode-select --install. -- OR --
Alternatively, if you already have the [full Xcode installed](https://developer.apple.com/xcode/download/), you can install the Command Line Tools under the menu Xcode -> Open Developer Tool -> More Developer Tools....

**Comment by pfrazee** [comment]
```
/home/raphy/.nvm/versions/node/v16.15.0/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: 5: /home/raphy/.nvm/versions/node/v14.17.0/lib/node_modules/node-gyp/bin/node-gyp.js: not found
```

This seems like it could be a clue. Why is it looking in the node 14.17 directory when youre running node 16.15?
